// <auto-generated />
using System;
using ImpalaFarming.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImpalaFarming.Migrations
{
    [DbContext(typeof(ImpalaFarmingDB))]
    [Migration("20200422005738_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ImpalaFarming.Models.CreditCardInfo", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cvv_number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("expiry_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("number");

                    b.ToTable("CreditCardInfos");
                });

            modelBuilder.Entity("ImpalaFarming.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderHistoryid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cart_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("TEXT");

                    b.Property<string>("delivery_address")
                        .HasColumnType("TEXT");

                    b.Property<double>("discount")
                        .HasColumnType("REAL");

                    b.Property<double>("total_price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("OrderHistoryid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ImpalaFarming.Models.OrderHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("OrderHistories");
                });

            modelBuilder.Entity("ImpalaFarming.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("available_in_stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("ShoppingCartid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ImpalaFarming.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("product_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ImpalaFarming.Models.ShoppingCart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("TEXT");

                    b.Property<double>("total_price")
                        .HasColumnType("REAL");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ImpalaFarming.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("province")
                        .HasColumnType("TEXT");

                    b.Property<string>("street_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("zip_code")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ImpalaFarming.Models.Order", b =>
                {
                    b.HasOne("ImpalaFarming.Models.OrderHistory", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderHistoryid");
                });

            modelBuilder.Entity("ImpalaFarming.Models.Product", b =>
                {
                    b.HasOne("ImpalaFarming.Models.ShoppingCart", null)
                        .WithMany("Products")
                        .HasForeignKey("ShoppingCartid");
                });
#pragma warning restore 612, 618
        }
    }
}
